import type { FirRecord, HealthResponse, SummaryResponse } from "./fir-api";

export const demoRecords: FirRecord[] = [
  {
    id: 42,
    fir_number: "0125/2024",
    police_station: "BARRACKPORE",
    district: "BARRACKPORE POLICE COMMISSIONERATE",
    fir_date: "15/03/2024",
    fir_time: "14:30 hrs",
    incident_date: "14/03/2024",
    incident_time: "22:00 hrs",
    legal_sections: "379, 411",
    complainant: "Suman Chakraborty",
    complainant_father: "Late Ratan Chakraborty",
    address: "23/1 Station Road, Barrackpore",
    accused: "Unknown",
    property: "Gold, jewellery, cash",
    total_value: "2,50,000",
    summary:
      "Suman Chakraborty reported the theft of gold jewellery and cash from her residence in Barrackpore on the night of 14 March 2024. The accused is unknown. The estimated value of the property is Rs. 2,50,000.",
    ocr_text: "Section 12: The complainant states that unknown persons entered the residence and removed gold jewellery and cash.",
    created_at: "2024-03-15 14:35:22",
  },
  {
    id: 41,
    fir_number: "0088/2024",
    police_station: "SALT LAKE",
    district: "BIDHANNAGAR COMMISSIONERATE",
    fir_date: "12/03/2024",
    fir_time: "09:10 hrs",
    incident_date: "11/03/2024",
    incident_time: "08:45 hrs",
    legal_sections: "420, 468, 471",
    complainant: "Ananya Sen",
    complainant_father: "Amit Sen",
    address: "Sector V, Salt Lake",
    accused: "R. Das and associates",
    property: "Digital funds",
    total_value: "85,000",
    summary:
      "Ananya Sen reported a suspected online financial fraud involving unauthorized transfers from her account. The complaint was registered at Salt Lake police station under sections 420, 468 and 471.",
    ocr_text: "The complainant noticed unauthorized digital transfers and submitted transaction details to the police station.",
    created_at: "2024-03-12 09:20:04",
  },
  {
    id: 40,
    fir_number: "0042/2024",
    police_station: "PARK STREET",
    district: "KOLKATA POLICE",
    fir_date: "08/03/2024",
    fir_time: "19:25 hrs",
    incident_date: "08/03/2024",
    incident_time: "18:50 hrs",
    legal_sections: "323, 341, 506",
    complainant: "Md. Imran Ali",
    complainant_father: "Md. Salim Ali",
    address: "Park Street, Kolkata",
    accused: "Known person",
    property: "Not applicable",
    total_value: "Not available",
    summary:
      "Md. Imran Ali reported an altercation near Park Street during the evening of 8 March 2024. The complaint alleges wrongful restraint, assault and criminal intimidation by a known person.",
    ocr_text: "Complaint regarding an altercation near Park Street and alleged threats made by a known person.",
    created_at: "2024-03-08 19:31:46",
  },
  {
    id: 39,
    fir_number: "0197/2023",
    police_station: "HOWRAH",
    district: "HOWRAH CITY POLICE",
    fir_date: "28/12/2023",
    fir_time: "11:40 hrs",
    incident_date: "27/12/2023",
    incident_time: "20:15 hrs",
    legal_sections: "457, 380",
    complainant: "Priyanka Roy",
    complainant_father: "Subhash Roy",
    address: "Shibpur, Howrah",
    accused: "Unknown",
    property: "Laptop, camera and documents",
    total_value: "1,10,000",
    summary:
      "Priyanka Roy reported a night-time house-breaking incident at her Shibpur residence. A laptop, camera and important documents were allegedly taken by unknown persons.",
    ocr_text: "House-breaking complaint with missing laptop, camera and documents.",
    created_at: "2023-12-28 11:52:10",
  },
  {
    id: 38,
    fir_number: "0112/2023",
    police_station: "DUM DUM",
    district: "NORTH 24 PARGANAS",
    fir_date: "19/11/2023",
    fir_time: "16:05 hrs",
    incident_date: "19/11/2023",
    incident_time: "13:00 hrs",
    legal_sections: "379",
    complainant: "Arijit Ghosh",
    complainant_father: "Bimal Ghosh",
    address: "Dum Dum Cantonment",
    accused: "Unknown",
    property: "Motorcycle",
    total_value: "95,000",
    summary:
      "Arijit Ghosh reported that his motorcycle was missing from Dum Dum Cantonment during the afternoon of 19 November 2023. The accused remains unknown.",
    ocr_text: "Motorcycle theft reported from Dum Dum Cantonment.",
    created_at: "2023-11-19 16:12:33",
  },
];

export const demoHealth: HealthResponse = { status: "ok", model_loaded: true, records: 35 };

export const demoSummary: SummaryResponse = {
  original_text:
    "FIRST INFORMATION REPORT. Police Station: Barrackpore. The complainant Suman Chakraborty reports that unknown persons entered her residence on 14/03/2024 at approximately 22:00 hrs and removed gold jewellery and cash. Total estimated value Rs. 2,50,000.",
  narrative:
    "The complainant states that unknown persons entered her residence in Barrackpore on the night of 14 March 2024 and removed gold jewellery and cash valued at approximately Rs. 2,50,000.",
  summary:
    "Suman Chakraborty reported that unknown persons entered her residence in Barrackpore on 14 March 2024 at approximately 22:00 hrs. Gold jewellery and cash were allegedly removed from the premises. The total estimated value of the missing property is Rs. 2,50,000. The complaint was registered at Barrackpore police station. The accused have not been identified at this stage. The matter has been recorded under legal sections 379 and 411.",
  translated_summary:
    "सुमन चक्रवर्ती ने बताया कि 14 मार्च 2024 को लगभग 22:00 बजे अज्ञात व्यक्ति उनके बैरकपुर स्थित घर में घुसे। सोने के आभूषण और नकद राशि ले जाने की सूचना है। संपत्ति का अनुमानित कुल मूल्य 2,50,000 रुपये है। शिकायत बैरकपुर थाने में दर्ज की गई है। इस समय आरोपी की पहचान नहीं हुई है। मामला धारा 379 और 411 के तहत दर्ज किया गया है।",
  translation_status: "ok",
  translation_note: null,
  target_language: "hi",
  metadata: {
    "FIR Number": "0125/2024",
    "Police Station": "BARRACKPORE",
    District: "BARRACKPORE POLICE COMMISSIONERATE",
    "FIR Date": "15/03/2024",
    "FIR Time": "14:30 hrs",
    "Incident Date": "14/03/2024",
    "Incident Time": "22:00 hrs",
    "Legal Sections": "379, 411",
    "Complainant Name": "Suman Chakraborty",
    "Complainant Father": "Late Ratan Chakraborty",
    Address: "23/1 Station Road, Barrackpore",
    Accused: "Unknown",
    Property: "Gold, jewellery, cash",
    "Total Value (Rs)": "2,50,000",
  },
};