import { Link } from "@tanstack/react-router";
import { ChevronRight, Copy, Download, FileText, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { FirRecord, SummaryResponse } from "@/lib/fir-api";

export function valueOrFallback(value: unknown) { return value === null || value === undefined || value === "" || value === "Not available" ? "Not explicitly stated" : String(value); }

export function RecordTable({ records, emptyMessage = "No FIR records match this search." }: { records: FirRecord[]; emptyMessage?: string }) {
  if (!records.length) return <div className="portal-panel flex flex-col items-center justify-center px-6 py-16 text-center"><FileText className="mb-3 size-8 text-muted-foreground/50" /><h3 className="font-serif text-lg font-bold">No records found</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">{emptyMessage}</p></div>;
  return <div className="portal-panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border bg-muted/65 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3 font-semibold">FIR number</th><th className="px-5 py-3 font-semibold">Complainant</th><th className="px-5 py-3 font-semibold">Station / district</th><th className="px-5 py-3 font-semibold">Registered</th><th className="px-5 py-3 font-semibold">Sections</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-border">{records.map((record) => <tr key={record.id} className="group transition-colors hover:bg-muted/40"><td className="px-5 py-4 align-top"><Link to="/search/fir" search={{ q: record.fir_number }} className="portal-focus font-semibold text-primary underline-offset-4 hover:underline">{record.fir_number}</Link><span className="mt-1 block text-xs text-muted-foreground">#{record.id}</span></td><td className="px-5 py-4 align-top"><span className="font-medium">{valueOrFallback(record.complainant)}</span><span className="mt-1 block max-w-[220px] truncate text-xs text-muted-foreground">{valueOrFallback(record.accused)}</span></td><td className="px-5 py-4 align-top"><span className="flex items-center gap-1.5 font-medium"><MapPin className="size-3.5 text-chart-1" />{valueOrFallback(record.police_station)}</span><span className="mt-1 block max-w-[220px] truncate text-xs text-muted-foreground">{valueOrFallback(record.district)}</span></td><td className="whitespace-nowrap px-5 py-4 align-top text-muted-foreground">{valueOrFallback(record.fir_date)}<span className="mt-1 block text-xs">{valueOrFallback(record.fir_time)}</span></td><td className="px-5 py-4 align-top"><Badge variant="secondary" className="font-mono text-[11px]">{valueOrFallback(record.legal_sections)}</Badge></td><td className="px-4 py-4 text-right"><Link to="/search/fir" search={{ q: record.fir_number }} className="portal-focus inline-flex size-8 items-center justify-center rounded-md text-muted-foreground opacity-70 hover:bg-accent hover:text-accent-foreground group-hover:opacity-100" aria-label={`Inspect FIR ${record.fir_number}`}><ChevronRight className="size-4" /></Link></td></tr>)}</tbody></table></div></div>;
}

export function MetadataGrid({ metadata }: { metadata: Record<string, string> }) {
  return <div className="grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{Object.entries(metadata).map(([label, value]) => <div key={label} className="bg-card px-4 py-3"><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm font-medium text-foreground">{valueOrFallback(value)}</dd></div>)}</div>;
}

export async function copyText(text: string) { await navigator.clipboard.writeText(text); }

export function SummaryActions({ summary, filename = "fir-summary.txt" }: { summary: SummaryResponse; filename?: string }) {
  const content = `FIR SUMMARY\n\n${summary.summary}\n\nMETADATA\n${Object.entries(summary.metadata).map(([key, value]) => `${key}: ${value}`).join("\n")}`;
  const download = () => { const blob = new Blob([content], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => void copyText(content)}><Copy /> Copy summary</Button><Button variant="outline" size="sm" onClick={download}><Download /> Download .txt</Button></div>;
}

export function RecordDetail({ record }: { record: FirRecord }) { return <div className="portal-panel p-5"><div className="flex flex-col justify-between gap-3 border-b border-border pb-4 sm:flex-row"><div><p className="portal-kicker">FIR record</p><h2 className="mt-1 font-serif text-2xl font-bold">{record.fir_number}</h2></div><Badge variant="secondary">Registered {record.fir_date}</Badge></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Complainant</dt><dd className="mt-1 text-sm font-medium">{valueOrFallback(record.complainant)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Accused</dt><dd className="mt-1 text-sm font-medium">{valueOrFallback(record.accused)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Station</dt><dd className="mt-1 text-sm font-medium">{valueOrFallback(record.police_station)}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Legal sections</dt><dd className="mt-1 text-sm font-medium">{valueOrFallback(record.legal_sections)}</dd></div></dl><div className="mt-5 border-t border-border pt-4"><p className="text-xs uppercase tracking-wider text-muted-foreground">Summary</p><p className="mt-2 text-sm leading-7 text-foreground/85">{valueOrFallback(record.summary)}</p></div></div>; }